[package]
name = "rm-rfp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rm-rfp"
path = "rm-rfp.rs"

[dependencies]
anyhow = "1"
indicatif = "0.17"
docopt = "1"
serde = { version = "1.0", features = ["derive"] } # for docopt

[dev-dependencies]
tempfile = "3"
